# Generated by Django 4.2.2 on 2023-06-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='home/images')),
            ],
        ),
    ]
