# Generated by Django 4.2.2 on 2023-07-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='example',
        ),
    ]
