# Generated by Django 4.2.2 on 2023-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='inside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='example',
            name='name',
        ),
    ]
