# Generated by Django 4.2.2 on 2023-07-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_inside_remove_example_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='example',
        ),
        migrations.DeleteModel(
            name='inside',
        ),
    ]
