# Generated by Django 4.2.2 on 2023-07-03 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_example_delete_inside'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ProductType',
        ),
    ]
