# Generated by Django 4.2.2 on 2023-07-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
