# Generated by Django 4.2.2 on 2023-07-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_products_company_products_quantity_products_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateProducts',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='home/images')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('sub_description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField(default='0')),
                ('quality', models.CharField(max_length=250, null=True)),
                ('company', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrickProducts',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='home/images')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=50)),
                ('minimum_order', models.IntegerField(default='0')),
                ('material', models.CharField(max_length=250, null=True)),
                ('Brand', models.CharField(max_length=50, null=True)),
                ('thickness', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CementProducts',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='home/images')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('sub_description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default='0')),
                ('type', models.CharField(max_length=250, null=True)),
                ('company', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DustProducts',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='home/images')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('sub_description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('quality', models.CharField(max_length=250, null=True)),
                ('source', models.CharField(max_length=250, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('supply_ability', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JamunaSnadProducts',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='home/images')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('sub_description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
