# Generated by Django 4.2.2 on 2023-07-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CementProducts',
            new_name='Products',
        ),
        migrations.DeleteModel(
            name='AggregateProducts',
        ),
        migrations.DeleteModel(
            name='BrickProducts',
        ),
        migrations.DeleteModel(
            name='DustProducts',
        ),
        migrations.DeleteModel(
            name='JamunaSnadProducts',
        ),
    ]
